// Local Host
### Get all contacts
GET http://localhost:3001/users

### Get users by contact ID

GET http://localhost:3000/users/696ecb3c8f8306846c518acc

### Create Contact
POST http://localhost:3001/users HTTP/1.1
content-type: application/json

{   
    "firstName": "Michael",
    "lastName": "White",
    "email": "whiteeeeMichael@test.com",
    "favoriteColor": "blue",
    "birthday": "9-10-1993"
}

### PUT contact
PUT http://localhost:3000/users/696ecb3c8f8306846c518acc
content-type: application/json

{
    "firstName": "Michael",
    "lastName": "White",
    "email": "michael.white@test.com",
    "favoriteColor": "blue",
    "birthday": "9-10-1993"
}

### Delete contact
DELETE http://localhost:3001/users/696edf377ba964ac90140e41